on:
  push:
    branches:
      - main

env:
  s3bucketname: lambda-unit-test-3053

jobs:
  create-S3-bucket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Upload to S3
        continue-on-error: true

        run: |
          aws s3 mb s3://$s3bucketname
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

  upload-input-data-to-s3:
    needs: create-S3-bucket
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ env.s3bucketname }}
          source_dir: 'data'
          destination_dir: 'input_data'

  run-unit-test:
    needs: upload-input-data-to-s3
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.9
          uses: actions/setup-python@v4
          with:
            # Semantic version range syntax or exact version of a Python version
            python-version: '3.9'
            # Optional - x64 or x86 architecture, defaults to x64
            architecture: 'x64'
        # You can test your matrix by printing the current Python version
        - name: Display Python version
          run: python -c "import sys; print(sys.version)"
        - name: Run unit test
          working-directory: ./tests
          run: |
            python -m unittest discover -s ./unit  -p 'test_*.py'
